-- 为 ElementUI 表单组件配置 PropertyConfigJson（右侧属性面板动态渲染）
-- 格式：DynPropContainer -> DynPropItem[] -> DynPropControl

-- DynElInput 输入框
UPDATE ComponentMeta SET PropertyConfigJson = '{"component":"DynPropContainer","options":{"itemoptions":{"style":{"padding":"0 8px"}},"childrenctrls":[{"component":"DynPropItem","modelname":"options.comoptions.placeholder","options":{"comoptions":{},"labeloptions":{"label":"占位符","show":true,"labelwidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"input","default":""},"itemoptions":{"style":{}}},"childrenctrls":[]}]},{"component":"DynPropItem","modelname":"options.comoptions.clearable","options":{"comoptions":{},"labeloptions":{"label":"可清除","show":true,"labelwidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"switch","default":true},"itemoptions":{"style":{}}},"childrenctrls":[]}]},{"component":"DynPropItem","modelname":"options.comoptions.disabled","options":{"comoptions":{},"labeloptions":{"label":"禁用","show":true,"labelwidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"switch","default":false},"itemoptions":{"style":{}}},"childrenctrls":[]}]},{"component":"DynPropItem","modelname":"options.comoptions.readonly","options":{"comoptions":{},"labeloptions":{"label":"只读","show":true,"labelwidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"switch","default":false},"itemoptions":{"style":{}}},"childrenctrls":[]}]},{"component":"DynPropItem","modelname":"options.comoptions.maxlength","options":{"comoptions":{},"labeloptions":{"label":"最大长度","show":true,"labelwidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"number","default":200},"itemoptions":{"style":{}}},"childrenctrls":[]}]}]}' WHERE ComponentName = 'DynElInput';

-- DynElTextarea 多行文本
UPDATE ComponentMeta SET PropertyConfigJson = '{"component":"DynPropContainer","options":{"itemoptions":{"style":{"padding":"0 8px"}},"childrenctrls":[{"component":"DynPropItem","modelname":"options.comoptions.placeholder","options":{"comoptions":{},"labeloptions":{"label":"占位符","show":true,"labelwidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"input","default":""},"itemoptions":{"style":{}}},"childrenctrls":[]}]},{"component":"DynPropItem","modelname":"options.comoptions.rows","options":{"comoptions":{},"labeloptions":{"label":"行数","show":true,"labelwidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"number","default":3},"itemoptions":{"style":{}}},"childrenctrls":[]}]},{"component":"DynPropItem","modelname":"options.comoptions.maxlength","options":{"comoptions":{},"labeloptions":{"label":"最大长度","show":true,"labelwidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"number","default":500},"itemoptions":{"style":{}}},"childrenctrls":[]}]}]}' WHERE ComponentName = 'DynElTextarea';

-- DynElSelect 下拉选择
UPDATE ComponentMeta SET PropertyConfigJson = '{"component":"DynPropContainer","options":{"itemoptions":{"style":{"padding":"0 8px"}},"childrenctrls":[{"component":"DynPropItem","modelname":"options.comoptions.placeholder","options":{"comoptions":{},"labeloptions":{"label":"占位符","show":true,"labelwidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"input","default":"请选择"},"itemoptions":{"style":{}}},"childrenctrls":[]}]},{"component":"DynPropItem","modelname":"options.comoptions.clearable","options":{"comoptions":{},"labeloptions":{"label":"可清除","show":true,"labelwidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"switch","default":true},"itemoptions":{"style":{}}},"childrenctrls":[]}]},{"component":"DynPropItem","modelname":"options.comoptions.multiple","options":{"comoptions":{},"labeloptions":{"label":"多选","show":true,"labelwidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"switch","default":false},"itemoptions":{"style":{}}},"childrenctrls":[]}]}]}' WHERE ComponentName = 'DynElSelect';

-- DynElSwitch 开关
UPDATE ComponentMeta SET PropertyConfigJson = '{"component":"DynPropContainer","options":{"itemoptions":{"style":{"padding":"0 8px"}},"childrenctrls":[{"component":"DynPropItem","modelname":"options.comoptions.activeText","options":{"comoptions":{},"labeloptions":{"label":"开启文字","show":true,"labelwidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"input","default":"开启"},"itemoptions":{"style":{}}},"childrenctrls":[]}]},{"component":"DynPropItem","modelname":"options.comoptions.inactiveText","options":{"comoptions":{},"labeloptions":{"label":"关闭文字","show":true,"labelwidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"input","default":"关闭"},"itemoptions":{"style":{}}},"childrenctrls":[]}]}]}' WHERE ComponentName = 'DynElSwitch';

-- DynElNumberInput 数字输入
UPDATE ComponentMeta SET PropertyConfigJson = '{"component":"DynPropContainer","options":{"itemoptions":{"style":{"padding":"0 8px"}},"childrenctrls":[{"component":"DynPropItem","modelname":"options.comoptions.placeholder","options":{"comoptions":{},"labeloptions":{"label":"占位符","show":true,"labelwidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"input","default":""},"itemoptions":{"style":{}}},"childrenctrls":[]}]},{"component":"DynPropItem","modelname":"options.comoptions.min","options":{"comoptions":{},"labeloptions":{"label":"最小值","show":true,"labelwidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"number","default":0},"itemoptions":{"style":{}}},"childrenctrls":[]}]},{"component":"DynPropItem","modelname":"options.comoptions.max","options":{"comoptions":{},"labeloptions":{"label":"最大值","show":true,"labelwidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"number","default":100},"itemoptions":{"style":{}}},"childrenctrls":[]}]}]}' WHERE ComponentName = 'DynElNumberInput';

-- DynElDatePicker 日期选择
UPDATE ComponentMeta SET PropertyConfigJson = '{"component":"DynPropContainer","options":{"itemoptions":{"style":{"padding":"0 8px"}},"childrenctrls":[{"component":"DynPropItem","modelname":"options.comoptions.placeholder","options":{"comoptions":{},"labeloptions":{"label":"占位符","show":true,"labelwidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"input","default":"请选择日期"},"itemoptions":{"style":{}}},"childrenctrls":[]}]},{"component":"DynPropItem","modelname":"options.comoptions.type","options":{"comoptions":{},"labeloptions":{"label":"类型","show":true,"labelwidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"select","default":"date","optionValues":[{"label":"日期","value":"date"},{"label":"日期时间","value":"datetime"},{"label":"周","value":"week"},{"label":"月份","value":"month"},{"label":"年份","value":"year"}],"itemoptions":{"style":{}}},"childrenctrls":[]}]}]}' WHERE ComponentName = 'DynElDatePicker';

-- DynElButton 按钮
UPDATE ComponentMeta SET PropertyConfigJson = '{"component":"DynPropContainer","options":{"itemoptions":{"style":{"padding":"0 8px"}},"childrenctrls":[{"component":"DynPropItem","modelname":"options.comoptions.type","options":{"comoptions":{},"labeloptions":{"label":"按钮类型","show":true,"labelwidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"select","default":"primary","optionValues":[{"label":"主要","value":"primary"},{"label":"成功","value":"success"},{"label":"警告","value":"warning"},{"label":"危险","value":"danger"},{"label":"默认","value":"default"}],"itemoptions":{"style":{}}},"childrenctrls":[]}]},{"component":"DynPropItem","modelname":"options.comoptions.plain","options":{"comoptions":{},"labeloptions":{"label":"朴素","show":true,"labelwidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"switch","default":false},"itemoptions":{"style":{}}},"childrenctrls":[]}]},{"component":"DynPropItem","modelname":"options.comoptions.round","options":{"comoptions":{},"labeloptions":{"label":"圆角","show":true,"labelwidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"switch","default":false},"itemoptions":{"style":{}}},"childrenctrls":[]}]}]}' WHERE ComponentName = 'DynElButton';


-- ==========================================================
-- 8个常用组件 PropertyConfigJson 【修复版】
-- 幂等：仅PropertyConfigJson IS NULL才更新，不覆盖已有配置
-- 修复：DynElSelect子控件 comoptions 不再误入 labeloptions 节点
-- ==========================================================
-- 1. DynElInput 单行输入
UPDATE ComponentMeta SET PropertyConfigJson='{"component":"DynElContainer","options":{"comoptions":{"direction":"vertical"},"labeloptions":{"show":false}},"childrenctrls":[{"component":"DynElSelect","modelname":"options.comoptions.size","options":{"labeloptions":{"label":"控件尺寸","show":true},"comoptions":{"sourceType":"static","optionValuesText":"large,大\ndefault,默认\nsmall,小"}}},{"component":"DynElSwitch","modelname":"options.comoptions.disabled","options":{"labeloptions":{"label":"禁用","show":true}}},{"component":"DynElInput","modelname":"options.comoptions.placeholder","options":{"labeloptions":{"label":"占位提示","show":true}}},{"component":"DynElSwitch","modelname":"options.comoptions.clearable","options":{"labeloptions":{"label":"可清空","show":true}}},{"component":"DynElSwitch","modelname":"options.comoptions.readonly","options":{"labeloptions":{"label":"只读","show":true}}},{"component":"DynElInputNumber","modelname":"options.comoptions.maxlength","options":{"comoptions":{"min":0},"labeloptions":{"label":"最大长度","show":true}}},{"component":"DynElSwitch","modelname":"options.comoptions.showWordLimit","options":{"labeloptions":{"label":"显示字数统计","show":true}}},{"component":"DynElInput","modelname":"options.comoptions.name","options":{"labeloptions":{"label":"原生Name","show":true}}},{"component":"DynElInput","modelname":"options.comoptions.prefix","options":{"labeloptions":{"label":"前缀图标","show":true}}},{"component":"DynElInput","modelname":"options.comoptions.suffix","options":{"labeloptions":{"label":"后缀图标","show":true}}},{"component":"DynElSwitch","modelname":"options.comoptions.showPassword","options":{"labeloptions":{"label":"密码框","show":true}}}]}' WHERE ComponentName='DynElInput' ;

-- 2. DynElInputNumber 数字输入
UPDATE ComponentMeta SET PropertyConfigJson='{"component":"DynElContainer","options":{"comoptions":{"direction":"vertical"},"labeloptions":{"show":false}},"childrenctrls":[{"component":"DynElSelect","modelname":"options.comoptions.size","options":{"labeloptions":{"label":"控件尺寸","show":true},"comoptions":{"sourceType":"static","optionValuesText":"large,大\ndefault,默认\nsmall,小"}}},{"component":"DynElSwitch","modelname":"options.comoptions.disabled","options":{"labeloptions":{"label":"禁用","show":true}}},{"component":"DynElInputNumber","modelname":"options.comoptions.min","options":{"labeloptions":{"label":"最小值","show":true}}},{"component":"DynElInputNumber","modelname":"options.comoptions.max","options":{"labeloptions":{"label":"最大值","show":true}}},{"component":"DynElInputNumber","modelname":"options.comoptions.step","options":{"labeloptions":{"label":"步长","show":true}}},{"component":"DynElSwitch","modelname":"options.comoptions.readonly","options":{"labeloptions":{"label":"只读","show":true}}},{"component":"DynElInputNumber","modelname":"options.comoptions.precision","options":{"comoptions":{"min":0},"labeloptions":{"label":"精度","show":true}}},{"component":"DynElInput","modelname":"options.comoptions.name","options":{"labeloptions":{"label":"原生Name","show":true}}},{"component":"DynElSwitch","modelname":"options.comoptions.controls","options":{"labeloptions":{"label":"显示加减按钮","show":true}}},{"component":"DynElSelect","modelname":"options.comoptions.controlsPosition","options":{"labeloptions":{"label":"按钮位置","show":true},"comoptions":{"sourceType":"static","optionValuesText":"right,右侧\nsides,两侧"}}}]}' WHERE ComponentName='DynElInputNumber' ;

--3. DynElTextarea 文本域
UPDATE ComponentMeta SET PropertyConfigJson='{"component":"DynElContainer","options":{"comoptions":{"direction":"vertical"},"labeloptions":{"show":false}},"childrenctrls":[{"component":"DynElSelect","modelname":"options.comoptions.size","options":{"labeloptions":{"label":"控件尺寸","show":true},"comoptions":{"sourceType":"static","optionValuesText":"large,大\ndefault,默认\nsmall,小"}}},{"component":"DynElSwitch","modelname":"options.comoptions.disabled","options":{"labeloptions":{"label":"禁用","show":true}}},{"component":"DynElInput","modelname":"options.comoptions.placeholder","options":{"labeloptions":{"label":"占位提示","show":true}}},{"component":"DynElSwitch","modelname":"options.comoptions.readonly","options":{"labeloptions":{"label":"只读","show":true}}},{"component":"DynElInputNumber","modelname":"options.comoptions.maxlength","options":{"comoptions":{"min":0},"labeloptions":{"label":"最大长度","show":true}}},{"component":"DynElSwitch","modelname":"options.comoptions.showWordLimit","options":{"labeloptions":{"label":"显示字数统计","show":true}}},{"component":"DynElInputNumber","modelname":"options.comoptions.rows","options":{"comoptions":{"min":1,"max":30},"labeloptions":{"label":"行数","show":true}}},{"component":"DynElInput","modelname":"options.comoptions.name","options":{"labeloptions":{"label":"原生Name","show":true}}},{"component":"DynElSwitch","modelname":"options.comoptions.autosize","options":{"labeloptions":{"label":"自动高度","show":true}}}]}' WHERE ComponentName='DynElTextarea' ;

--4. DynElSelect 下拉选择
UPDATE ComponentMeta SET PropertyConfigJson='{"component":"DynElContainer","options":{"comoptions":{"direction":"vertical"},"labeloptions":{"show":false}},"childrenctrls":[{"component":"DynElSelect","modelname":"options.comoptions.size","options":{"labeloptions":{"label":"控件尺寸","show":true},"comoptions":{"sourceType":"static","optionValuesText":"large,大\ndefault,默认\nsmall,小"}}},{"component":"DynElSwitch","modelname":"options.comoptions.disabled","options":{"labeloptions":{"label":"禁用","show":true}}},{"component":"DynElSelect","modelname":"options.comoptions.sourceType","options":{"labeloptions":{"label":"数据源类型","show":true},"comoptions":{"sourceType":"static","optionValuesText":"static,静态\ndict,字典\ntable,数据表\najax,远程接口"}}},{"component":"DynElSwitch","modelname":"options.comoptions.clearable","options":{"labeloptions":{"label":"可清空","show":true}}},{"component":"DynElSwitch","modelname":"options.comoptions.filterable","options":{"labeloptions":{"label":"可搜索","show":true}}},{"component":"DynElSwitch","modelname":"options.comoptions.multiple","options":{"labeloptions":{"label":"多选","show":true}}},{"component":"DynElInput","modelname":"options.comoptions.placeholder","options":{"labeloptions":{"label":"占位提示","show":true}}},{"component":"DynElInput","modelname":"options.comoptions.name","options":{"labeloptions":{"label":"原生Name","show":true}}},{"component":"DynElTextarea","modelname":"options.comoptions.optionValuesText","options":{"labeloptions":{"label":"静态选项(值,文本换行)","show":true}}},{"component":"DynElInput","modelname":"options.comoptions.dictType","options":{"labeloptions":{"label":"字典编码","show":true}}}]}' WHERE ComponentName='DynElSelect' ;

--5. DynElRadioGroup 单选组
UPDATE ComponentMeta SET PropertyConfigJson='{"component":"DynElContainer","options":{"comoptions":{"direction":"vertical"},"labeloptions":{"show":false}},"childrenctrls":[{"component":"DynElSelect","modelname":"options.comoptions.size","options":{"labeloptions":{"label":"控件尺寸","show":true},"comoptions":{"sourceType":"static","optionValuesText":"large,大\ndefault,默认\nsmall,小"}}},{"component":"DynElSwitch","modelname":"options.comoptions.disabled","options":{"labeloptions":{"label":"禁用","show":true}}},{"component":"DynElSelect","modelname":"options.comoptions.type","options":{"labeloptions":{"label":"单选组类型","show":true},"comoptions":{"sourceType":"static","optionValuesText":"radio,圆点单选\nbutton,按钮单选"}}},{"component":"DynElSelect","modelname":"options.comoptions.sourceType","options":{"labeloptions":{"label":"数据源类型","show":true},"comoptions":{"sourceType":"static","optionValuesText":"static,静态\ndict,字典\ntable,数据表\najax,远程接口"}}},{"component":"DynElSwitch","modelname":"options.comoptions.readonly","options":{"labeloptions":{"label":"只读","show":true}}},{"component":"DynElInput","modelname":"options.comoptions.placeholder","options":{"labeloptions":{"label":"占位提示","show":true}}},{"component":"DynElInput","modelname":"options.comoptions.name","options":{"labeloptions":{"label":"原生Name","show":true}}},{"component":"DynElTextarea","modelname":"options.comoptions.optionValuesText","options":{"labeloptions":{"label":"静态选项(值,文本换行)","show":true}}},{"component":"DynElInput","modelname":"options.comoptions.dictType","options":{"labeloptions":{"label":"字典编码","show":true}}}]}' WHERE ComponentName='DynElRadioGroup' ;

--6. DynElCheckboxGroup 复选组【重点修复】
UPDATE ComponentMeta SET PropertyConfigJson='{"component":"DynElContainer","options":{"comoptions":{"direction":"vertical"},"labeloptions":{"show":false}},"childrenctrls":[{"component":"DynElSelect","modelname":"options.comoptions.size","options":{"labeloptions":{"label":"控件尺寸","show":true},"comoptions":{"sourceType":"static","optionValuesText":"large,大\ndefault,默认\nsmall,小"}}},{"component":"DynElSwitch","modelname":"options.comoptions.disabled","options":{"labeloptions":{"label":"禁用","show":true}}},{"component":"DynElSelect","modelname":"options.comoptions.type","options":{"labeloptions":{"label":"复选组类型","show":true},"comoptions":{"sourceType":"static","optionValuesText":"checkbox,方框复选\nbutton,按钮复选"}}},{"component":"DynElSelect","modelname":"options.comoptions.sourceType","options":{"labeloptions":{"label":"数据源类型","show":true},"comoptions":{"sourceType":"static","optionValuesText":"static,静态\ndict,字典\ntable,数据表\najax,远程接口"}}},{"component":"DynElSwitch","modelname":"options.comoptions.readonly","options":{"labeloptions":{"label":"只读","show":true}}},{"component":"DynElInput","modelname":"options.comoptions.placeholder","options":{"labeloptions":{"label":"占位提示","show":true}}},{"component":"DynElInput","modelname":"options.comoptions.name","options":{"labeloptions":{"label":"原生Name","show":true}}},{"component":"DynElTextarea","modelname":"options.comoptions.optionValuesText","options":{"labeloptions":{"label":"静态选项(值,文本换行)","show":true}}},{"component":"DynElInput","modelname":"options.comoptions.dictType","options":{"labeloptions":{"label":"字典编码","show":true}}}]}' WHERE ComponentName='DynElCheckboxGroup' ;

--7. DynElSwitch 开关
UPDATE ComponentMeta SET PropertyConfigJson='{"component":"DynElContainer","options":{"comoptions":{"direction":"vertical"},"labeloptions":{"show":false}},"childrenctrls":[{"component":"DynElSelect","modelname":"options.comoptions.size","options":{"labeloptions":{"label":"控件尺寸","show":true},"comoptions":{"sourceType":"static","optionValuesText":"large,大\ndefault,默认\nsmall,小"}}},{"component":"DynElSwitch","modelname":"options.comoptions.disabled","options":{"labeloptions":{"label":"禁用","show":true}}},{"component":"DynElInput","modelname":"options.comoptions.activeText","options":{"labeloptions":{"label":"打开文字","show":true}}},{"component":"DynElInput","modelname":"options.comoptions.inactiveText","options":{"labeloptions":{"label":"关闭文字","show":true}}},{"component":"DynElInput","modelname":"options.comoptions.activeValue","options":{"labeloptions":{"label":"打开值","show":true}}},{"component":"DynElInput","modelname":"options.comoptions.inactiveValue","options":{"labeloptions":{"label":"关闭值","show":true}}},{"component":"DynElInput","modelname":"options.comoptions.name","options":{"labeloptions":{"label":"原生Name","show":true}}},{"component":"DynElSwitch","modelname":"options.comoptions.readonly","options":{"labeloptions":{"label":"只读","show":true}}}]}' WHERE ComponentName='DynElSwitch' ;

--8. DynElDatePicker 日期选择
UPDATE ComponentMeta SET PropertyConfigJson='{"component":"DynElContainer","options":{"comoptions":{"direction":"vertical"},"labeloptions":{"show":false}},"childrenctrls":[{"component":"DynElSelect","modelname":"options.comoptions.size","options":{"labeloptions":{"label":"控件尺寸","show":true},"comoptions":{"sourceType":"static","optionValuesText":"large,大\ndefault,默认\nsmall,小"}}},{"component":"DynElSwitch","modelname":"options.comoptions.disabled","options":{"labeloptions":{"label":"禁用","show":true}}},{"component":"DynElSelect","modelname":"options.comoptions.type","options":{"labeloptions":{"label":"日期类型","show":true},"comoptions":{"sourceType":"static","optionValuesText":"date,日期\ndaterange,日期范围\ndatetime,日期时间\ndatetimerange,日期时间范围"}}},{"component":"DynElInput","modelname":"options.comoptions.placeholder","options":{"labeloptions":{"label":"占位提示","show":true}}},{"component":"DynElSwitch","modelname":"options.comoptions.readonly","options":{"labeloptions":{"label":"只读","show":true}}},{"component":"DynElSwitch","modelname":"options.comoptions.clearable","options":{"labeloptions":{"label":"可清空","show":true}}},{"component":"DynElInput","modelname":"options.comoptions.format","options":{"labeloptions":{"label":"显示格式","show":true}}},{"component":"DynElInput","modelname":"options.comoptions.name","options":{"labeloptions":{"label":"原生Name","show":true}}},{"component":"DynElInput","modelname":"options.comoptions.valueFormat","options":{"labeloptions":{"label":"值格式","show":true}}}]}' WHERE ComponentName='DynElDatePicker' ;
