-- 为 ElementUI 表单组件配置 PropertyConfigJson（右侧属性面板动态渲染）
-- 格式：DynPropContainer -> DynPropItem[] -> DynPropControl

-- DynElInput 输入框
UPDATE ComponentMeta SET PropertyConfigJson = '{"component":"DynPropContainer","options":{"itemoptions":{"style":{"padding":"0 8px"}},"childrenctrls":[{"component":"DynPropItem","modelname":"options.comoptions.placeholder","options":{"comoptions":{"label":"占位符","showLabel":true,"labelWidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"input","default":""},"itemoptions":{"style":{}}},"childrenctrls":[]}]},{"component":"DynPropItem","modelname":"options.comoptions.clearable","options":{"comoptions":{"label":"可清除","showLabel":true,"labelWidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"switch","default":true},"itemoptions":{"style":{}}},"childrenctrls":[]}]},{"component":"DynPropItem","modelname":"options.comoptions.disabled","options":{"comoptions":{"label":"禁用","showLabel":true,"labelWidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"switch","default":false},"itemoptions":{"style":{}}},"childrenctrls":[]}]},{"component":"DynPropItem","modelname":"options.comoptions.readonly","options":{"comoptions":{"label":"只读","showLabel":true,"labelWidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"switch","default":false},"itemoptions":{"style":{}}},"childrenctrls":[]}]},{"component":"DynPropItem","modelname":"options.comoptions.maxlength","options":{"comoptions":{"label":"最大长度","showLabel":true,"labelWidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"number","default":200},"itemoptions":{"style":{}}},"childrenctrls":[]}]}]}' WHERE ComponentName = 'DynElInput';

-- DynElTextarea 多行文本
UPDATE ComponentMeta SET PropertyConfigJson = '{"component":"DynPropContainer","options":{"itemoptions":{"style":{"padding":"0 8px"}},"childrenctrls":[{"component":"DynPropItem","modelname":"options.comoptions.placeholder","options":{"comoptions":{"label":"占位符","showLabel":true,"labelWidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"input","default":""},"itemoptions":{"style":{}}},"childrenctrls":[]}]},{"component":"DynPropItem","modelname":"options.comoptions.rows","options":{"comoptions":{"label":"行数","showLabel":true,"labelWidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"number","default":3},"itemoptions":{"style":{}}},"childrenctrls":[]}]},{"component":"DynPropItem","modelname":"options.comoptions.maxlength","options":{"comoptions":{"label":"最大长度","showLabel":true,"labelWidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"number","default":500},"itemoptions":{"style":{}}},"childrenctrls":[]}]}]}' WHERE ComponentName = 'DynElTextarea';

-- DynElSelect 下拉选择
UPDATE ComponentMeta SET PropertyConfigJson = '{"component":"DynPropContainer","options":{"itemoptions":{"style":{"padding":"0 8px"}},"childrenctrls":[{"component":"DynPropItem","modelname":"options.comoptions.placeholder","options":{"comoptions":{"label":"占位符","showLabel":true,"labelWidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"input","default":"请选择"},"itemoptions":{"style":{}}},"childrenctrls":[]}]},{"component":"DynPropItem","modelname":"options.comoptions.clearable","options":{"comoptions":{"label":"可清除","showLabel":true,"labelWidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"switch","default":true},"itemoptions":{"style":{}}},"childrenctrls":[]}]},{"component":"DynPropItem","modelname":"options.comoptions.multiple","options":{"comoptions":{"label":"多选","showLabel":true,"labelWidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"switch","default":false},"itemoptions":{"style":{}}},"childrenctrls":[]}]}]}' WHERE ComponentName = 'DynElSelect';

-- DynElSwitch 开关
UPDATE ComponentMeta SET PropertyConfigJson = '{"component":"DynPropContainer","options":{"itemoptions":{"style":{"padding":"0 8px"}},"childrenctrls":[{"component":"DynPropItem","modelname":"options.comoptions.activeText","options":{"comoptions":{"label":"开启文字","showLabel":true,"labelWidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"input","default":"开启"},"itemoptions":{"style":{}}},"childrenctrls":[]}]},{"component":"DynPropItem","modelname":"options.comoptions.inactiveText","options":{"comoptions":{"label":"关闭文字","showLabel":true,"labelWidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"input","default":"关闭"},"itemoptions":{"style":{}}},"childrenctrls":[]}]}]}' WHERE ComponentName = 'DynElSwitch';

-- DynElNumberInput 数字输入
UPDATE ComponentMeta SET PropertyConfigJson = '{"component":"DynPropContainer","options":{"itemoptions":{"style":{"padding":"0 8px"}},"childrenctrls":[{"component":"DynPropItem","modelname":"options.comoptions.placeholder","options":{"comoptions":{"label":"占位符","showLabel":true,"labelWidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"input","default":""},"itemoptions":{"style":{}}},"childrenctrls":[]}]},{"component":"DynPropItem","modelname":"options.comoptions.min","options":{"comoptions":{"label":"最小值","showLabel":true,"labelWidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"number","default":0},"itemoptions":{"style":{}}},"childrenctrls":[]}]},{"component":"DynPropItem","modelname":"options.comoptions.max","options":{"comoptions":{"label":"最大值","showLabel":true,"labelWidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"number","default":100},"itemoptions":{"style":{}}},"childrenctrls":[]}]}]}' WHERE ComponentName = 'DynElNumberInput';

-- DynElDatePicker 日期选择
UPDATE ComponentMeta SET PropertyConfigJson = '{"component":"DynPropContainer","options":{"itemoptions":{"style":{"padding":"0 8px"}},"childrenctrls":[{"component":"DynPropItem","modelname":"options.comoptions.placeholder","options":{"comoptions":{"label":"占位符","showLabel":true,"labelWidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"input","default":"请选择日期"},"itemoptions":{"style":{}}},"childrenctrls":[]}]},{"component":"DynPropItem","modelname":"options.comoptions.type","options":{"comoptions":{"label":"类型","showLabel":true,"labelWidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"select","default":"date","optionValues":[{"label":"日期","value":"date"},{"label":"日期时间","value":"datetime"},{"label":"周","value":"week"},{"label":"月份","value":"month"},{"label":"年份","value":"year"}],"itemoptions":{"style":{}}},"childrenctrls":[]}]}]}' WHERE ComponentName = 'DynElDatePicker';

-- DynElButton 按钮
UPDATE ComponentMeta SET PropertyConfigJson = '{"component":"DynPropContainer","options":{"itemoptions":{"style":{"padding":"0 8px"}},"childrenctrls":[{"component":"DynPropItem","modelname":"options.comoptions.type","options":{"comoptions":{"label":"按钮类型","showLabel":true,"labelWidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"select","default":"primary","optionValues":[{"label":"主要","value":"primary"},{"label":"成功","value":"success"},{"label":"警告","value":"warning"},{"label":"危险","value":"danger"},{"label":"默认","value":"default"}],"itemoptions":{"style":{}}},"childrenctrls":[]}]},{"component":"DynPropItem","modelname":"options.comoptions.plain","options":{"comoptions":{"label":"朴素","showLabel":true,"labelWidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"switch","default":false},"itemoptions":{"style":{}}},"childrenctrls":[]}]},{"component":"DynPropItem","modelname":"options.comoptions.round","options":{"comoptions":{"label":"圆角","showLabel":true,"labelWidth":"80px"},"itemoptions":{"style":{"marginBottom":"8px"}}},"childrenctrls":[{"component":"DynPropControl","modelname":"","options":{"comoptions":{"kind":"switch","default":false},"itemoptions":{"style":{}}},"childrenctrls":[]}]}]}' WHERE ComponentName = 'DynElButton';
