UPDATE ComponentMeta SET
  DefaultConfigJson = N'{"component":"DynElGrid3","modelname":"","options":{"comoptions":{"pageTitle":"数据管理","featureUrl":"/DynCommon/DynCommon","projectId":1,"pageId":3,"detailPageId":4,"defaultLoad":true,"showSearch":true,"showClear":true,"showAdd":true},"comlisteners":{},"labeloptions":{"label":"","required":false,"show":true},"itemoptions":{"style":{},"class":""},"wrapperoptions":{}},"validators":[],"childrenctrls":[],"slots":{},"extendinfo":{}}',
  DefaultOptionsJson = N'{"comoptions":{"pageTitle":"数据管理","featureUrl":"/DynCommon/DynCommon","projectId":1,"pageId":3,"detailPageId":4,"defaultLoad":true,"showSearch":true,"showClear":true,"showAdd":true}}',
  [Description] = N'3屏管理组件：Filter(筛选面板)+Grid(列表/分页)+Detail(新增/编辑/删除)。配置 featureUrl 后自动取 功能URL/FilterPanel、功能URL/ListPanel、功能URL/Detail、功能URL/Data/Delete，各 URL 可单独覆盖。',
  PropertyConfigJson = N'{"groups":[{"title":"基本设置","fields":[{"key":"options.comoptions.pageTitle","label":"页面标题","type":"input","default":"数据管理"},{"key":"options.comoptions.featureUrl","label":"功能URL","type":"input","placeholder":"如 /DynCommon/DynCommon"},{"key":"options.comoptions.projectId","label":"工程Id","type":"input-number","default":1},{"key":"options.comoptions.pageId","label":"列表页Id","type":"input-number","default":3},{"key":"options.comoptions.detailPageId","label":"详情页Id","type":"input-number","default":4}]},{"title":"功能URL（可单独覆盖）","fields":[{"key":"options.comoptions.filterUrl","label":"FilterURL","type":"input","placeholder":"默认 功能URL/FilterPanel"},{"key":"options.comoptions.listUrl","label":"ListURL","type":"input","placeholder":"默认 功能URL/ListPanel"},{"key":"options.comoptions.editUrl","label":"EditURL","type":"input","placeholder":"默认 功能URL/Detail"},{"key":"options.comoptions.addUrl","label":"AddURL","type":"input","placeholder":"默认 功能URL/Detail"},{"key":"options.comoptions.deleteUrl","label":"DeleteURL","type":"input","placeholder":"默认 功能URL/Data/Delete"}]},{"title":"显示与行为","fields":[{"key":"options.comoptions.defaultLoad","label":"默认加载汇总","type":"switch","default":true},{"key":"options.comoptions.showSearch","label":"显示搜索按钮","type":"switch","default":true},{"key":"options.comoptions.showClear","label":"显示清除按钮","type":"switch","default":true},{"key":"options.comoptions.showAdd","label":"显示添加按钮","type":"switch","default":true}]}]}',
  Icon = N'📋', Label = N'3屏管理', IsEnabled = 1
WHERE ComponentName = 'DynElGrid3';

IF NOT EXISTS (SELECT 1 FROM PageSetting WHERE PageCode = 'grid3-demo')
INSERT INTO PageSetting (PageName, PageCode, Category, Icon, ConfigJson, DefaultModelJson, ApiBaseUrl, [Description], IsEnabled, SortOrder, CreatedAt, UpdatedAt, Platform, CustomScriptJson, CanvasWidth, CanvasHeight)
VALUES (N'3屏管理组件Demo', 'grid3-demo', N'模板', N'📋',
  N'{"component":"DynElGrid3","modelname":"","options":{"comoptions":{"pageTitle":"客户管理","featureUrl":"/DynCommon/DynCommon","projectId":1,"pageId":3,"detailPageId":4,"defaultLoad":true,"showSearch":true,"showClear":true,"showAdd":true},"comlisteners":{},"labeloptions":{},"itemoptions":{"style":{"padding":"16px"},"class":""}},"validators":[],"childrenctrls":[],"slots":{},"extendinfo":{}}',
  NULL, '/DynCommon',
  N'3屏管理组件（Filter+Grid+Detail）演示：筛选→搜索→列表加载；清除→重置筛选；添加/编辑→模态表单；删除→确认删除。数据源：工程1(SunnySystem) 页面3(客户列表)/4(客户编辑)。',
  1, 1, GETDATE(), GETDATE(), 'desktop', NULL, 1280, 800);