/* ============================================================
 * VueLib 低代码平台 - ElementUI 表单组件属性配置（完整重写）
 * 对齐 NutUI 实现方式：完整 UPDATE 替换，分组用 title 字段
 * 每个组件包含：基础属性 + 标签配置 + 样式
 * ============================================================ */
USE VueLib;
GO

-- DynElInput
UPDATE dbo.ComponentMeta SET PropertyConfigJson = N'{"groups":[{"title":"基础属性","fields":[{"key":"options.comoptions.placeholder","label":"占位符","type":"input","default":"请输入"},{"key":"options.comoptions.type","label":"类型","type":"select","default":"text","options":[{"label":"文本","value":"text"},{"label":"密码","value":"password"},{"label":"多行","value":"textarea"},{"label":"数字","value":"number"}]},{"key":"options.comoptions.clearable","label":"可清空","type":"switch","default":false},{"key":"options.comoptions.disabled","label":"禁用","type":"switch","default":false},{"key":"options.comoptions.readonly","label":"只读","type":"switch","default":false},{"key":"options.comoptions.maxlength","label":"最大长度","type":"number","default":0},{"key":"options.comoptions.showWordLimit","label":"显示字数","type":"switch","default":false}]},{"title":"标签配置","fields":[{"key":"options.labeloptions.label","label":"标签文字","type":"input","default":""},{"key":"options.labeloptions.required","label":"必填","type":"switch","default":false},{"key":"options.labeloptions.show","label":"显示标签","type":"switch","default":true},{"key":"options.labeloptions.labelWidth","label":"标签宽度","type":"input","default":""}]},{"title":"样式","fields":[{"key":"options.itemoptions.style.width","label":"宽度","type":"input","default":"100%"},{"key":"options.itemoptions.style.marginTop","label":"上边距","type":"input","default":""},{"key":"options.itemoptions.style.marginBottom","label":"下边距","type":"input","default":""},{"key":"options.itemoptions.class","label":"自定义类名","type":"input","default":""}]}]}' WHERE ComponentName = N'DynElInput';

-- DynElInputNumber
UPDATE dbo.ComponentMeta SET PropertyConfigJson = N'{"groups":[{"title":"基础属性","fields":[{"key":"options.comoptions.min","label":"最小值","type":"number","default":0},{"key":"options.comoptions.max","label":"最大值","type":"number","default":100},{"key":"options.comoptions.step","label":"步长","type":"number","default":1},{"key":"options.comoptions.precision","label":"精度","type":"number","default":0},{"key":"options.comoptions.disabled","label":"禁用","type":"switch","default":false},{"key":"options.comoptions.controlsPosition","label":"按钮位置","type":"select","default":"","options":[{"label":"默认","value":""},{"label":"两侧","value":"right"}]}]},{"title":"标签配置","fields":[{"key":"options.labeloptions.label","label":"标签文字","type":"input","default":""},{"key":"options.labeloptions.required","label":"必填","type":"switch","default":false},{"key":"options.labeloptions.show","label":"显示标签","type":"switch","default":true},{"key":"options.labeloptions.labelWidth","label":"标签宽度","type":"input","default":""}]},{"title":"样式","fields":[{"key":"options.itemoptions.style.width","label":"宽度","type":"input","default":"100%"},{"key":"options.itemoptions.style.marginTop","label":"上边距","type":"input","default":""},{"key":"options.itemoptions.style.marginBottom","label":"下边距","type":"input","default":""},{"key":"options.itemoptions.class","label":"自定义类名","type":"input","default":""}]}]}' WHERE ComponentName = N'DynElInputNumber';

-- DynElSelect
UPDATE dbo.ComponentMeta SET PropertyConfigJson = N'{"groups":[{"title":"基础属性","fields":[{"key":"options.comoptions.placeholder","label":"占位符","type":"input","default":"请选择"},{"key":"options.comoptions.clearable","label":"可清空","type":"switch","default":true},{"key":"options.comoptions.disabled","label":"禁用","type":"switch","default":false},{"key":"options.comoptions.multiple","label":"多选","type":"switch","default":false},{"key":"options.comoptions.filterable","label":"可搜索","type":"switch","default":false},{"key":"options.optionValues","label":"选项(逗号分隔)","type":"input","default":"选项1,选项2"}]},{"title":"标签配置","fields":[{"key":"options.labeloptions.label","label":"标签文字","type":"input","default":""},{"key":"options.labeloptions.required","label":"必填","type":"switch","default":false},{"key":"options.labeloptions.show","label":"显示标签","type":"switch","default":true},{"key":"options.labeloptions.labelWidth","label":"标签宽度","type":"input","default":""}]},{"title":"样式","fields":[{"key":"options.itemoptions.style.width","label":"宽度","type":"input","default":"100%"},{"key":"options.itemoptions.style.marginTop","label":"上边距","type":"input","default":""},{"key":"options.itemoptions.style.marginBottom","label":"下边距","type":"input","default":""},{"key":"options.itemoptions.class","label":"自定义类名","type":"input","default":""}]}]}' WHERE ComponentName = N'DynElSelect';

-- DynElSwitch
UPDATE dbo.ComponentMeta SET PropertyConfigJson = N'{"groups":[{"title":"基础属性","fields":[{"key":"options.comoptions.disabled","label":"禁用","type":"switch","default":false},{"key":"options.comoptions.loading","label":"加载中","type":"switch","default":false},{"key":"options.comoptions.size","label":"尺寸","type":"select","default":"default","options":[{"label":"大","value":"large"},{"label":"默认","value":"default"},{"label":"小","value":"small"}]},{"key":"options.comoptions.activeText","label":"开启文字","type":"input","default":""},{"key":"options.comoptions.inactiveText","label":"关闭文字","type":"input","default":""},{"key":"options.comoptions.activeColor","label":"开启颜色","type":"color","default":"#409EFF"},{"key":"options.comoptions.inactiveColor","label":"关闭颜色","type":"color","default":"#C0CCDA"}]},{"title":"标签配置","fields":[{"key":"options.labeloptions.label","label":"标签文字","type":"input","default":""},{"key":"options.labeloptions.required","label":"必填","type":"switch","default":false},{"key":"options.labeloptions.show","label":"显示标签","type":"switch","default":true},{"key":"options.labeloptions.labelWidth","label":"标签宽度","type":"input","default":""}]},{"title":"样式","fields":[{"key":"options.itemoptions.style.width","label":"宽度","type":"input","default":"100%"},{"key":"options.itemoptions.style.marginTop","label":"上边距","type":"input","default":""},{"key":"options.itemoptions.style.marginBottom","label":"下边距","type":"input","default":""},{"key":"options.itemoptions.class","label":"自定义类名","type":"input","default":""}]}]}' WHERE ComponentName = N'DynElSwitch';

-- DynElRadio
UPDATE dbo.ComponentMeta SET PropertyConfigJson = N'{"groups":[{"title":"基础属性","fields":[{"key":"options.comoptions.disabled","label":"禁用","type":"switch","default":false},{"key":"options.comoptions.size","label":"尺寸","type":"select","default":"default","options":[{"label":"大","value":"large"},{"label":"默认","value":"default"},{"label":"小","value":"small"}]},{"key":"options.comoptions.textColor","label":"选中文字色","type":"color","default":"#ffffff"},{"key":"options.comoptions.fill","label":"选中填充色","type":"color","default":"#409EFF"},{"key":"options.optionValues","label":"选项(逗号分隔)","type":"input","default":"选项1,选项2,选项3"}]},{"title":"标签配置","fields":[{"key":"options.labeloptions.label","label":"标签文字","type":"input","default":""},{"key":"options.labeloptions.required","label":"必填","type":"switch","default":false},{"key":"options.labeloptions.show","label":"显示标签","type":"switch","default":true},{"key":"options.labeloptions.labelWidth","label":"标签宽度","type":"input","default":""}]},{"title":"样式","fields":[{"key":"options.itemoptions.style.width","label":"宽度","type":"input","default":"100%"},{"key":"options.itemoptions.style.marginTop","label":"上边距","type":"input","default":""},{"key":"options.itemoptions.style.marginBottom","label":"下边距","type":"input","default":""},{"key":"options.itemoptions.class","label":"自定义类名","type":"input","default":""}]}]}' WHERE ComponentName = N'DynElRadio';

-- DynElCheckbox
UPDATE dbo.ComponentMeta SET PropertyConfigJson = N'{"groups":[{"title":"基础属性","fields":[{"key":"options.comoptions.disabled","label":"禁用","type":"switch","default":false},{"key":"options.comoptions.size","label":"尺寸","type":"select","default":"default","options":[{"label":"大","value":"large"},{"label":"默认","value":"default"},{"label":"小","value":"small"}]},{"key":"options.comoptions.min","label":"最少选中","type":"number","default":0},{"key":"options.comoptions.max","label":"最多选中","type":"number","default":0},{"key":"options.comoptions.textColor","label":"选中文字色","type":"color","default":"#ffffff"},{"key":"options.comoptions.fill","label":"选中填充色","type":"color","default":"#409EFF"},{"key":"options.optionValues","label":"选项(逗号分隔)","type":"input","default":"选项1,选项2,选项3"}]},{"title":"标签配置","fields":[{"key":"options.labeloptions.label","label":"标签文字","type":"input","default":""},{"key":"options.labeloptions.required","label":"必填","type":"switch","default":false},{"key":"options.labeloptions.show","label":"显示标签","type":"switch","default":true},{"key":"options.labeloptions.labelWidth","label":"标签宽度","type":"input","default":""}]},{"title":"样式","fields":[{"key":"options.itemoptions.style.width","label":"宽度","type":"input","default":"100%"},{"key":"options.itemoptions.style.marginTop","label":"上边距","type":"input","default":""},{"key":"options.itemoptions.style.marginBottom","label":"下边距","type":"input","default":""},{"key":"options.itemoptions.class","label":"自定义类名","type":"input","default":""}]}]}' WHERE ComponentName = N'DynElCheckbox';

-- DynElDatePicker
UPDATE dbo.ComponentMeta SET PropertyConfigJson = N'{"groups":[{"title":"基础属性","fields":[{"key":"options.comoptions.type","label":"类型","type":"select","default":"date","options":[{"label":"日期","value":"date"},{"label":"日期时间","value":"datetime"},{"label":"日期范围","value":"daterange"},{"label":"月份","value":"month"},{"label":"年份","value":"year"},{"label":"周","value":"week"}]},{"key":"options.comoptions.placeholder","label":"占位符","type":"input","default":"选择日期"},{"key":"options.comoptions.clearable","label":"可清空","type":"switch","default":true},{"key":"options.comoptions.disabled","label":"禁用","type":"switch","default":false},{"key":"options.comoptions.format","label":"显示格式","type":"input","default":"YYYY-MM-DD"},{"key":"options.comoptions.valueFormat","label":"值格式","type":"input","default":"YYYY-MM-DD"}]},{"title":"标签配置","fields":[{"key":"options.labeloptions.label","label":"标签文字","type":"input","default":""},{"key":"options.labeloptions.required","label":"必填","type":"switch","default":false},{"key":"options.labeloptions.show","label":"显示标签","type":"switch","default":true},{"key":"options.labeloptions.labelWidth","label":"标签宽度","type":"input","default":""}]},{"title":"样式","fields":[{"key":"options.itemoptions.style.width","label":"宽度","type":"input","default":"100%"},{"key":"options.itemoptions.style.marginTop","label":"上边距","type":"input","default":""},{"key":"options.itemoptions.style.marginBottom","label":"下边距","type":"input","default":""},{"key":"options.itemoptions.class","label":"自定义类名","type":"input","default":""}]}]}' WHERE ComponentName = N'DynElDatePicker';

-- DynElTimePicker
UPDATE dbo.ComponentMeta SET PropertyConfigJson = N'{"groups":[{"title":"基础属性","fields":[{"key":"options.comoptions.placeholder","label":"占位符","type":"input","default":"选择时间"},{"key":"options.comoptions.clearable","label":"可清空","type":"switch","default":true},{"key":"options.comoptions.disabled","label":"禁用","type":"switch","default":false},{"key":"options.comoptions.format","label":"格式","type":"input","default":"HH:mm:ss"},{"key":"options.comoptions.isRange","label":"范围选择","type":"switch","default":false}]},{"title":"标签配置","fields":[{"key":"options.labeloptions.label","label":"标签文字","type":"input","default":""},{"key":"options.labeloptions.required","label":"必填","type":"switch","default":false},{"key":"options.labeloptions.show","label":"显示标签","type":"switch","default":true},{"key":"options.labeloptions.labelWidth","label":"标签宽度","type":"input","default":""}]},{"title":"样式","fields":[{"key":"options.itemoptions.style.width","label":"宽度","type":"input","default":"100%"},{"key":"options.itemoptions.style.marginTop","label":"上边距","type":"input","default":""},{"key":"options.itemoptions.style.marginBottom","label":"下边距","type":"input","default":""},{"key":"options.itemoptions.class","label":"自定义类名","type":"input","default":""}]}]}' WHERE ComponentName = N'DynElTimePicker';

-- DynElSlider
UPDATE dbo.ComponentMeta SET PropertyConfigJson = N'{"groups":[{"title":"基础属性","fields":[{"key":"options.comoptions.min","label":"最小值","type":"number","default":0},{"key":"options.comoptions.max","label":"最大值","type":"number","default":100},{"key":"options.comoptions.step","label":"步长","type":"number","default":1},{"key":"options.comoptions.disabled","label":"禁用","type":"switch","default":false},{"key":"options.comoptions.showInput","label":"显示输入框","type":"switch","default":false},{"key":"options.comoptions.showStops","label":"显示间断点","type":"switch","default":false},{"key":"options.comoptions.range","label":"范围选择","type":"switch","default":false},{"key":"options.comoptions.vertical","label":"竖向","type":"switch","default":false}]},{"title":"标签配置","fields":[{"key":"options.labeloptions.label","label":"标签文字","type":"input","default":""},{"key":"options.labeloptions.required","label":"必填","type":"switch","default":false},{"key":"options.labeloptions.show","label":"显示标签","type":"switch","default":true},{"key":"options.labeloptions.labelWidth","label":"标签宽度","type":"input","default":""}]},{"title":"样式","fields":[{"key":"options.itemoptions.style.width","label":"宽度","type":"input","default":"100%"},{"key":"options.itemoptions.style.marginTop","label":"上边距","type":"input","default":""},{"key":"options.itemoptions.style.marginBottom","label":"下边距","type":"input","default":""},{"key":"options.itemoptions.class","label":"自定义类名","type":"input","default":""}]}]}' WHERE ComponentName = N'DynElSlider';

-- DynElRate
UPDATE dbo.ComponentMeta SET PropertyConfigJson = N'{"groups":[{"title":"基础属性","fields":[{"key":"options.comoptions.max","label":"最大分值","type":"number","default":5},{"key":"options.comoptions.disabled","label":"禁用","type":"switch","default":false},{"key":"options.comoptions.allowHalf","label":"允许半选","type":"switch","default":false},{"key":"options.comoptions.showText","label":"显示文字","type":"switch","default":false},{"key":"options.comoptions.showScore","label":"显示分数","type":"switch","default":false},{"key":"options.comoptions.textColor","label":"文字颜色","type":"color","default":"#ff9900"},{"key":"options.comoptions.voidColor","label":"未选中颜色","type":"color","default":"#C6D1DE"}]},{"title":"标签配置","fields":[{"key":"options.labeloptions.label","label":"标签文字","type":"input","default":""},{"key":"options.labeloptions.required","label":"必填","type":"switch","default":false},{"key":"options.labeloptions.show","label":"显示标签","type":"switch","default":true},{"key":"options.labeloptions.labelWidth","label":"标签宽度","type":"input","default":""}]},{"title":"样式","fields":[{"key":"options.itemoptions.style.width","label":"宽度","type":"input","default":"100%"},{"key":"options.itemoptions.style.marginTop","label":"上边距","type":"input","default":""},{"key":"options.itemoptions.style.marginBottom","label":"下边距","type":"input","default":""},{"key":"options.itemoptions.class","label":"自定义类名","type":"input","default":""}]}]}' WHERE ComponentName = N'DynElRate';

-- DynElColorPicker
UPDATE dbo.ComponentMeta SET PropertyConfigJson = N'{"groups":[{"title":"基础属性","fields":[{"key":"options.comoptions.disabled","label":"禁用","type":"switch","default":false},{"key":"options.comoptions.size","label":"尺寸","type":"select","default":"default","options":[{"label":"大","value":"large"},{"label":"默认","value":"default"},{"label":"小","value":"small"}]},{"key":"options.comoptions.showAlpha","label":"显示透明度","type":"switch","default":false},{"key":"options.comoptions.colorFormat","label":"颜色格式","type":"select","default":"hex","options":[{"label":"HEX","value":"hex"},{"label":"RGB","value":"rgb"},{"label":"HSL","value":"hsl"}]},{"key":"options.comoptions.predefine","label":"预定义颜色","type":"input","default":""}]},{"title":"标签配置","fields":[{"key":"options.labeloptions.label","label":"标签文字","type":"input","default":""},{"key":"options.labeloptions.required","label":"必填","type":"switch","default":false},{"key":"options.labeloptions.show","label":"显示标签","type":"switch","default":true},{"key":"options.labeloptions.labelWidth","label":"标签宽度","type":"input","default":""}]},{"title":"样式","fields":[{"key":"options.itemoptions.style.width","label":"宽度","type":"input","default":"100%"},{"key":"options.itemoptions.style.marginTop","label":"上边距","type":"input","default":""},{"key":"options.itemoptions.style.marginBottom","label":"下边距","type":"input","default":""},{"key":"options.itemoptions.class","label":"自定义类名","type":"input","default":""}]}]}' WHERE ComponentName = N'DynElColorPicker';

PRINT N'ElementUI 表单组件属性配置完整重写完成（11个）';
GO
