<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>VueLibV4.Platform</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VueLibV4.Services\VueLibV4.Services.csproj" />
  </ItemGroup>

</Project>
