// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesDataAnalyzer.Data;

#nullable disable

namespace SalesDataAnalyzer.Data.Migrations
{
    [DbContext(typeof(SalesDbContext))]
    [Migration("20260422175508_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SalesDataAnalyzer.Models.HourlySales", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FuelOnlyAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FuelOnlyCount")
                        .HasColumnType("int");

                    b.Property<int>("Hour")
                        .HasColumnType("int");

                    b.Property<decimal>("ItemCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MerchFuelAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MerchFuelCount")
                        .HasColumnType("int");

                    b.Property<decimal>("MerchOnlyAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MerchOnlyCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("PeriodBeginDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodEndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RegisterId")
                        .HasColumnType("int");

                    b.Property<int>("SiteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SiteId", "Hour", "PeriodBeginDate");

                    b.ToTable("HourlySales");
                });

            modelBuilder.Entity("SalesDataAnalyzer.Models.PaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CancelRefundAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CancelRefundCount")
                        .HasColumnType("int");

                    b.Property<int?>("CashierId")
                        .HasColumnType("int");

                    b.Property<string>("CashierName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCardBased")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PaymentSysId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PeriodBeginDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodEndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RegisterId")
                        .HasColumnType("int");

                    b.Property<decimal>("SaleAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SaleCount")
                        .HasColumnType("int");

                    b.Property<int>("SiteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SiteId", "PaymentSysId", "PeriodBeginDate");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("SalesDataAnalyzer.Models.SalesCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CashierId")
                        .HasColumnType("int");

                    b.Property<string>("CashierName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategorySysId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("NetSalesAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NetSalesCount")
                        .HasColumnType("int");

                    b.Property<decimal>("NetSalesItemCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PercentOfSales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PeriodBeginDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodEndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RegisterId")
                        .HasColumnType("int");

                    b.Property<int>("SiteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SiteId", "CategorySysId", "PeriodBeginDate");

                    b.ToTable("SalesCategories");
                });

            modelBuilder.Entity("SalesDataAnalyzer.Models.SalesSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CashierId")
                        .HasColumnType("int");

                    b.Property<string>("CashierName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerCount")
                        .HasColumnType("int");

                    b.Property<decimal>("FuelSales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InsideGrandDifference")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InsideGrandEnd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InsideGrandStart")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InsideSalesDifference")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InsideSalesEnd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InsideSalesStart")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ItemCount")
                        .HasColumnType("int");

                    b.Property<decimal>("MerchSales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetSales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NoSaleCount")
                        .HasColumnType("int");

                    b.Property<decimal>("OutsideGrandDifference")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OutsideGrandEnd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OutsideGrandStart")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OutsideSalesDifference")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OutsideSalesEnd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OutsideSalesStart")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PeriodBeginDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodEndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RegisterId")
                        .HasColumnType("int");

                    b.Property<int>("SiteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SiteId", "PeriodBeginDate");

                    b.ToTable("SalesSummaries");
                });

            modelBuilder.Entity("SalesDataAnalyzer.Models.VectorData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChromaDocumentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PeriodDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SiteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SiteId", "PeriodDate", "DataType");

                    b.ToTable("VectorData");
                });
#pragma warning restore 612, 618
        }
    }
}
